language: ruby
rvm:
  - 2.1.5
before_install:
  - "gem install bundler -v 1.6"
  - "cp config/instapaper.yml.example config/instapaper.yml"
  - "RAILS_ENV=test bin/rake db:create db:migrate"
script:
  - bundle exec rake
  - bundle exec rubocop

