source :rubygems
gem 'sinatra', '1.1.0'
gem 'thin'
gem 'progress_bar'
gem 'instapaper_full'
gem 'ruby-oembed'
gem 'markdown'
gem 'kramdown'
gem 'rack-flash'
gem 'pony'
gem 'mail'
gem 'shotgun'
gem 'sass'