default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: layabout_development

test: &test
  <<: *default
  database: layabout_test

production:
  <<: *default
  database: layabout_production
