# Be sure to restart your server when you modify this file.
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# If you want to run Layabout locally, you'll need to do the following
# request oauth credentials from Instapaper:
# https://www.instapaper.com/main/request_oauth_consumer_token
#
# run `cp config/instapaper.yml.example config/instapaper.yml`
# update config/instapaper.yml with your credentials

<%
  if Rails.env.production?
    instapaper = {
      'consumer_key' => ENV['INSTAPAPER_CONSUMER_KEY'],
      'consumer_secret' => ENV['INSTAPAPER_CONSUMER_SECRET']
    }
  else
    yaml = File.read(Rails.root.join('config', 'instapaper.yml'))
    instapaper = YAML.load(yaml)['instapaper']
  end
%>

defaults: &defaults
  instapaper:
    consumer_key: <%= instapaper['consumer_key'] %>
    consumer_secret: <%= instapaper['consumer_secret']  %>

development:
  secret_key_base: 499d187073f6c7c1d16b45f08fe5bda4ed1b03f8a9ee36a80842d7179868370d82b1f758cf0c7c271405a37b5745806f64aa2e214456fbff0c3bccaf39e65602
  <<: *defaults

test:
  secret_key_base: 7da7c479c1757c0716fc60634b03ef4589fea36cfec11d3aee4c9f8bd38f801bc4d337394326d5b2dffd77078f70f088b3338f909bf87e602b4c89314c9124de
  <<: *defaults

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  <<: *defaults

